<?php
	//Implementation of hook menu
function myview_menu() {
	$items = array();

	$items['view/myview'] = array(
		'title' => 'find a doctor',
		'description' => 'to create doctor page.',
		'page callback' => 'myviewpage',
		'access callback' => TRUE
	);

	return $items;
}

//FORM DROPDOWN LIST 

function mydropdown ($form, &$form_state){


$dropdown_source = db_select('taxonomy_term_data','t')
										->condition('t.tid',0,'<>')
										->fields('t',array('tid','name'))
										->execute();
$result = $dropdown_source->fetchAll();

foreach ($result as $key => $value) {
 // dpm($value);
	$id =$value->tid;
 // dpm($id);
	$names = $value->name;
 // dpm($names);
	$dropdown_array[$id] = $names;
}


$form['filterspec'] = array(
		'#weight' => '1',
		'#type' => 'select',
		'#options' => $dropdown_array,
		'#default_value' => '0',
		'#title' => 'Filter by speciality',);

$drophospitals = db_select('node','n')
								->condition('n.type','hospital_page','=')
								->fields('n',array('title'))
								->execute();

$result1 =$drophospitals->fetchAll();
foreach ($result1 as $key => $value1) {
	$namehos = $value1->title;
	$dropdown_arrayhos[] = $namehos;

}

$form['filterhos'] = array(
		'#weight' => '2',
		'#type' => 'select',
		'#options' => $dropdown_arrayhos,
		'#default_value' => 0,
		'#title' => 'Filter by hospitals',
	);
 
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
    '#weight' => '3',
  );
return $form;
}

function mydropdown_submit($form, &$form_state){
	$speciality_value = $form_state['values']['filterspec'];
	$hospital_value = $form_state['values']['filterhos'];
	drupal_goto('view/myview', array('query'=>array('specality_id' => $speciality_value, 'hospital_id'  => $hospital_value,)
	));

// $form_state['rebuild'] = TRUE;

}

// VIEW FOR DOCTOR FIELDS

function myview() {
$query_params = drupal_get_query_parameters();

$speciality_condition = $query_params['specality_id'];

$hospital_condition = $query_params['hospital_id'];


$query = new EntityFieldQuery();
// $form_value = drupal_get_form('mydropdown');
// dpm($form_value);

// $specl1 = $form_value['filterspec']['#value'];
// $hosp1  =$form_value['filterhos']['#value'];
$query->entityCondition('entity_type', 'node')
			->entityCondition('bundle', 'doctor');
			if(!empty($speciality_condition)){
				$query->fieldCondition('field_speciality', 'tid',$speciality_condition);
			}
			if(!empty($hospital_condition)){
				$query->fieldCondition('field_hospitals','value',$hospital_condition);
			}
	
$result2 = $query->execute();

$header = array(t('Doctor name'), t('Speciality Name'), t('Hospital'));
$rows = array();
foreach ($result2['node'] as $key => $value2) {
  $nid = $value2->nid;
  $doc = node_load($nid);
  $field_value = field_get_items('node', $doc, 'field_speciality')[0]['tid'];
  $field_value1= field_get_items('node', $doc, 'field_hospitals')[0]['target_id'];
    // dpm($doc->title);
  $docname = $doc->title;
  $spec = taxonomy_term_load($field_value);
  $hosp = node_load($field_value1);

      //dpm($spec->name);
    //  dpm($hosp->title);
  $speclname = $spec->name;
  $hospname = $hosp->title;
  $subrow = array();
  $subrow[] = $docname;
  $subrow[] = $speclname;
  $subrow[] = $hospname;
  $rows[] = $subrow;
}

	 return theme('table', array('header' => $header, 'rows' => $rows)); 

}

function myviewpage(){
	$filter_form = drupal_get_form('mydropdown');
	$output = render($filter_form);
	$output .= myview();
	return $output;
}